[package]
name = "libavif"
version = "0.1.0"
authors = ["Kalle Samuels <charles@derkarl.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libavif-sys={path= "libavif-sys" }

[dev-dependencies]
image="*"

