[package]
name = "libavif-sys"
version = "0.4.0"
authors = ["Kalle Samuels <charles@derkarl.org>"]
edition = "2018"
build = "build.rs"
description="Unsafe wrapper around libavif, the image codec"
keywords=["ffi","codec", "image", "avif", "AV1"]
repository="https://github.com/njaard/libavif"
documentation="https://docs.rs/libavif-sys"
license="BSD-2-Clause"
readme = "README.md"

[features]
default=["codec-dav1d", "codec-rav1e"]
codec-rav1e=["rav1e"]
codec-dav1d=["meson"]
codec-aom=[]

[dependencies]
libc="0.2"
rav1e = { version="0.3", features=["asm","capi"], optional=true}

[build-dependencies]
cmake = "0.1"
meson= {version="1", optional=true }

