name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUST_BACKTRACE: full

jobs:
  style:
    name: Check Style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          profile: minimal
          override: true

      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Check Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install nasm
        env:
          LINK: http://debian-archive.trafficmanager.net/debian/pool/main/n/nasm
          NASM_VERSION: 2.14.02-1
          NASM_SHA256: >-
            5225d0654783134ae616f56ce8649e4df09cba191d612a0300cfd0494bb5a3ef
        run: |
          curl -O "$LINK/nasm_${NASM_VERSION}_amd64.deb"
          echo "$NASM_SHA256 nasm_${NASM_VERSION}_amd64.deb" | sha256sum --check
          sudo dpkg -i "nasm_${NASM_VERSION}_amd64.deb"

      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ninja-build
          pip install --upgrade pip
          pip install meson

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          profile: minimal
          override: true

      - name: cargo clippy --all --examples
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --examples

  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    strategy:
      matrix:
        name:
          - linux / stable
          - linux / beta
          - linux / nightly
          - macOS / stable
          - "feat.: codec-aom"

        include:
          - name: linux / stable
            rust: stable
          - name: linux / beta
            rust: beta
          - name: linux / nightly
            rust: nightly

          - name: macOS / stable
            os: macOS-latest

          - name: "feat.: codec-aom"
            features: "--no-default-features --features codec-aom"

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install nasm (linux)
        if: matrix.os != 'macOS-latest'
        env:
          LINK: http://debian-archive.trafficmanager.net/debian/pool/main/n/nasm
          NASM_VERSION: 2.14.02-1
          NASM_SHA256: >-
            5225d0654783134ae616f56ce8649e4df09cba191d612a0300cfd0494bb5a3ef
        run: |
          curl -O "$LINK/nasm_${NASM_VERSION}_amd64.deb"
          echo "$NASM_SHA256 nasm_${NASM_VERSION}_amd64.deb" | sha256sum --check
          sudo dpkg -i "nasm_${NASM_VERSION}_amd64.deb"

      - name: Install dependencies (linux)
        if: matrix.os != 'macOS-latest'
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ninja-build
          pip install --upgrade pip
          pip install meson

      - name: Install dependencies (macOS)
        if: matrix.os == 'macOS-latest'
        run: |
          brew install ninja nasm
          pip install --upgrade pip
          pip install meson

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust || 'stable' }}
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: ${{ matrix.features }} --all --examples

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.features }} --all

  minversion:
    name: Minimum version ${{ matrix.rust }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [1.36.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install nasm
        env:
          LINK: http://debian-archive.trafficmanager.net/debian/pool/main/n/nasm
          NASM_VERSION: 2.14.02-1
          NASM_SHA256: >-
            5225d0654783134ae616f56ce8649e4df09cba191d612a0300cfd0494bb5a3ef
        run: |
          curl -O "$LINK/nasm_${NASM_VERSION}_amd64.deb"
          echo "$NASM_SHA256 nasm_${NASM_VERSION}_amd64.deb" | sha256sum --check
          sudo dpkg -i "nasm_${NASM_VERSION}_amd64.deb"

      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ninja-build
          pip install --upgrade pip
          pip install meson

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --examples
